### ISSUE TITLE
build error on ubuntu 18.04.02 / nodejs 10.15.1

### ISSUE THREAD

**Issue by sirmaciej** [tuxedocomputers/tuxedo-fan-control#13]
Hi folks, 

I followed the build steps as per the documentation at: https://github.com/tuxedocomputers/tuxedo-fan-control

However I can't build it:
```
$ npm run build
 
> tuxedofancontrol@0.1.4 build /tmp/tuxedo-fan-control
> npm run clean && node-gyp rebuild && ng build --base-href . && ts-node ./scripts/build.ts
 
 
> tuxedofancontrol@0.1.4 clean /tmp/tuxedo-fan-control
> rm -rf ./bin && rm -rf ./build && rm -rf ./output && rm -rf ./dist
 
internal/modules/cjs/loader.js:583
    throw err;
    ^
 
Error: Cannot find module 'node-addon-api'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at [eval]:1:1
    at Script.runInThisContext (vm.js:96:20)
    at Object.runInThisContext (vm.js:303:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at evalScript (internal/bootstrap/node.js:587:27)
gyp: Call to 'node -p "require('node-addon-api').include"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.15.0-44-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/tuxedo-fan-control
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tuxedofancontrol@0.1.4 build: `npm run clean && node-gyp rebuild && ng build --base-href . && ts-node ./scripts/build.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tuxedofancontrol@0.1.4 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
```

nodejs version:
```
$ nodejs --version
v10.15.1
```

Did I miss anything? thanks

**Comment by tuxedochris** [comment]
Hi sirmaciej,

have you call "npm install" before you execute "npm build"?

Cheers
Chris

**Comment by sirmaciej** [comment]
Thanks Chris, this fixed the issue. 👍
